// Generated by CoffeeScript 1.8.0
(function() {
  var $, displayCandidateContent, inputFocus, listToggle;

  $ = jQuery.noConflict();

  $(function() {
    inputFocus();
    listToggle();
    return displayCandidateContent();
  });

  listToggle = function() {
    var $listButtons;
    $listButtons = $('.list-view-controls button');
    return $listButtons.on('click', function(e) {
      var $click, $listContainer;
      $click = $(e.currentTarget);
      $listContainer = $('.list-container');
      if (!$click.hasClass('active')) {
        $listButtons.removeClass('active');
        $click.addClass('active');
        return $listContainer.toggleClass('list-view');
      }
    });
  };

  inputFocus = function() {
    var $input;
    $input = $('.input-holder input');
    $input.on('focus', function(e) {
      var $holder;
      $holder = $(this).parent('.input-holder');
      return $holder.addClass('focus');
    });
    return $input.on('blur', function() {
      return $('.input-holder').removeClass('focus');
    });
  };

  displayCandidateContent = function() {
    var $contentContainer, $navItems;
    $navItems = $('.candidate-content nav a');
    $contentContainer = $('.content-container');
    return $navItems.on('click', function(e) {
      var $activeContent, $click, activeContent;
      $click = $(e.currentTarget);
      activeContent = $click.data('content');
      console.log('activeContent', activeContent);
      $activeContent = $('.content-container[data-content="' + activeContent + '"]');
      console.log('$activeContent', $activeContent);
      $navItems.removeClass('active');
      $click.addClass('active');
      $contentContainer.removeClass('active');
      return $activeContent.addClass('active');
    });
  };

}).call(this);
